function ANEW=FITTNESSCACULATION(TE,DATACONDUC,ANEW,NS,NSPR,NP,AU,AL)

for I=1:NS-NSPR
    GENDATA(1:NP)=ANEW(I,1:NP);
    ANEW(I,NP+1)=FITTNESFUNCTION(TE,DATACONDUC,GENDATA,NP);
end
ANEW=sortrows(ANEW,-(NP+1));
